apiVersion: apps/v1
kind: Deployment
metadata:
  name: video processing
  labels:
    app: video processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video processing
  template:
    metadata:
      labels:
        app: video processing
    spec:
      containers:
        - name: video processing
//<<< Container / Image Name
          image: username/video processing:latest
//>>> Container / Image Name          
          ports:
            - containerPort: 8080

//<<< Availability / Zero Down Time

          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
//>>> Availability / Zero Down Time            
//<<< Availability / Self Healing
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
//>>> Availability / Self Healing